---
title: "MT5763_2_200030711"
author: "Alex Curtis"
date: "17/10/2020"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

GitHub repository can be found at: https://github.com/acurtis869/MT5763_2_200030711

## Abstract


## Introduction


## Methods
First the data set was transformed to make it easier to analyse. The data-wrangling comprised changing the table so that there were columns for treatment, hair growth and age, and also transforming the values for growth into millimetres from inches (as specified).
```
/* Import dataset */
FILENAME REFFILE '/folders/myshortcuts/SASUniversityEdition/myfolders/MT5763/Coursework 2/Baldy.csv';

PROC IMPORT DATAFILE=REFFILE
	DBMS=CSV
	OUT=MT5763.BALDYRAW;
	GETNAMES=YES;
RUN;

/* Transfrom data to make it easier to analyse */

/* Start by making a new table, with three columns for treatment, hair growth, and age */
/* Create temporary tables for each treatment */
DATA MT5763.LUXURIANT;
SET MT5763.BALDYRAW;
Treatment="Luxuriant";
Growth = Luxuriant;
Age = AgeLuxuriant;
KEEP Treatment Growth Age
RUN;

DATA MT5763.PLACEBO;
SET MT5763.BALDYRAW;
Treatment="Placebo";
Growth = Placebo;
Age = AgePlacebo;
KEEP Treatment Growth Age
RUN;

DATA MT5763.BALDBEGONE;
SET MT5763.BALDYRAW;
Treatment="BaldBeGone";
Growth = BaldBeGone;
Age = AgeBaldBeGone;
KEEP Treatment Growth Age
RUN;

DATA MT5763.SKINHEADNOMORE;
SET MT5763.BALDYRAW;
Treatment="Skinheadnomore";
Growth = Skinheadnomore;
Age = AgeSkinheadnomore;
KEEP Treatment Growth Age
RUN;

/* Now merge these temporary tables to create new table */
DATA MT5763.Baldy;
SET MT5763.LUXURIANT MT5763.PLACEBO MT5763.BALDBEGONE MT5763.SKINHEADNOMORE; 
RUN;

/* Transform growth from inches into mm */
DATA MT5763.Baldy;
SET MT5763.Baldy;
Growth = Growth * 25.4;
RUN;
```

In order to answer the questions posed, several plots were created to explore the data visually. To compare the effect of *Luxuriant* with that of the placebo and the other two treatments, the plots created were box-plots. These were chosen as they describe the distribution of the data very clearly and are very effective for performing an initial analysis. To explore the effect that age has, four scatter plots were produced (one for each treatment) and combined into a grid. This allows one to easily see if there is any relationship between age and hair growth for each treatment.

Further to creating the plots, a statistical procedure was performed for each question to provide further evidence to any initial conclusions. To compare between *Luxuriant* and the placebo, a two-sample t-test was used as this compares the means of the two samples and produces a p-value that can be used to provide evidence for whether *Luxuriant* has an effect or not. For the other two questions a linear model was produced to gauge the effect of the existing treatments or the age variable. To compare with the existing treatments, this was a simple linear model with treatment as the predictor variable. For the age model, age and an interaction term were also added to see if the effect of age is different for each treatment.


## Results


## Discussion


## References
